// Everything the suite reads, resolved from the repository rather than from an absolute
// path on whoever's machine wrote the test. The suite lived outside the repo for a long
// time and picked up hardcoded paths accordingly; this is the single place that knows
// where anything is.
const path = require("path");
const fs   = require("fs");

const REPO = path.resolve(__dirname, "..");
const HTML = process.env.WE_HTML || path.join(REPO, "warehouse-empire-android.html");

// app-ads.txt lives in the Pages repo, not this one, so the publisher-id cross-check can
// only run where both are checked out. Point WE_APP_ADS at it to enable that assertion;
// without it the test reports the check as skipped rather than passing on nothing.
const APP_ADS = process.env.WE_APP_ADS ||
  path.join(REPO, "..", "abdulalrubat-bit.github.io", "app-ads.txt");

module.exports = {
  REPO,
  HTML,
  HTML_URL: "file://" + HTML,
  APP_ADS,
  hasAppAds: () => { try { return fs.statSync(APP_ADS).isFile(); } catch(e){ return false; } },
  WORKFLOW: path.join(REPO, ".github", "workflows", "build-release.yml"),
  // Generated by extract.sh next to these tests.
  gen: name => path.join(__dirname, name)
};
