#!/usr/bin/env python3
"""Bake art/atlas.png + art/atlas.json into the shipping HTML as one inlined script.

The game is a single file: the workflow does `cp warehouse-empire-android.html
www/index.html` and nothing else, so a sibling atlas.png would simply not be in the
AAB. Inlining also keeps the file openable straight from a phone's Downloads folder,
which is how the first prototype broke.

WebP rather than PNG: the atlas is 589KB as PNG and 272KB as WebP at quality 95, with
a mean channel error under 1/255 over opaque pixels -- no banding, no ringing on the
alpha edges. Every WebView this ships to is Chromium. The PNG stays in art/ as the
source the pipeline regenerates.

    python3 tools/inline-atlas.py
"""
import base64, io, json, os, re, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HTML = os.path.join(ROOT, "warehouse-empire-android.html")
PNG = os.path.join(ROOT, "art", "atlas.png")
META = os.path.join(ROOT, "art", "atlas.json")
QUALITY = 95

im = Image.open(PNG).convert("RGBA")
# The packer leaves the bottom of the sheet empty. Cropping saves nothing much on disk
# but a great deal of texture memory: 2048x2048 RGBA is 16MB decoded, and the used
# extent is a little over half that.
box = im.getbbox()
used_h = min(im.height, (box[3] + 7) // 8 * 8)
im = im.crop((0, 0, im.width, used_h))

buf = io.BytesIO()
im.save(buf, format="WEBP", quality=QUALITY, method=6)
webp = buf.getvalue()

meta = json.load(open(META))
frames = {k: {"x": f["x"], "y": f["y"], "w": f["w"], "h": f["h"], "ax": f["ax"], "ay": f["ay"]}
          for k, f in meta["frames"].items()}
payload = {"tilePx": meta.get("tilePx", 48), "w": im.width, "h": im.height, "frames": frames}

block = (
    '<script id="atlas">\n'
    "/* Generated by tools/inline-atlas.py from art/atlas.png -- do not hand-edit. */\n"
    "window.__ATLAS=" + json.dumps(payload, separators=(",", ":")) + ";\n"
    'window.__ATLAS_IMG="data:image/webp;base64,' + base64.b64encode(webp).decode("ascii") + '";\n'
    "</script>"
)

src = open(HTML, encoding="utf-8").read()
existing = re.search(r'<script id="atlas">.*?</script>', src, re.S)
if existing:
    src = src[:existing.start()] + block + src[existing.end():]
else:
    # Ahead of the game script, so window.__ATLAS is there when the game boots.
    marker = "<script>\n(function(){"
    if marker not in src:
        sys.exit("could not find the game script to insert before")
    src = src.replace(marker, block + "\n" + marker, 1)
open(HTML, "w", encoding="utf-8").write(src)

print(f"atlas {im.width}x{im.height}, {len(frames)} frames")
print(f"png {os.path.getsize(PNG)/1024:.0f}KB -> webp q{QUALITY} {len(webp)/1024:.0f}KB "
      f"-> base64 {len(webp)*4/3/1024:.0f}KB")
print(f"html now {os.path.getsize(HTML)/1024:.0f}KB")
