#!/usr/bin/env python3
"""Bake the frames the game draws out of art/atlas.png into the shipping HTML.

The game is a single file: the workflow does `cp warehouse-empire-android.html
www/index.html` and nothing else, so a sibling atlas.png would simply not be in the
AAB. Inlining also keeps the file openable straight from a phone's Downloads folder,
which is how the first prototype broke.

WebP rather than PNG, at quality 95: a mean channel error under 1/255 over opaque
pixels, no banding and no ringing on the alpha edges. Every WebView this ships to is
Chromium. The full sheet stays in art/ as the source, so adding a model later is a
matter of naming it in KEEP and re-running this.

    python3 tools/inline-atlas.py
"""
import base64, io, json, os, re, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HTML = os.path.join(ROOT, "warehouse-empire-android.html")
PNG = os.path.join(ROOT, "art", "atlas.png")
META = os.path.join(ROOT, "art", "atlas.json")
QUALITY = 95

# Only the frames the game actually draws. The full sheet is 86 models and 265KB, and
# the game uses five of them: the site itself is drawn as blocks, because that is what
# the liveries recolour and what makes the yard read as this game. Repacking to the used
# set takes the payload from 265KB to a couple of kilobytes.
KEEP = ["forklift-0", "forklift-90", "forklift-180", "forklift-270", "box-large"]

src = Image.open(PNG).convert("RGBA")
meta = json.load(open(META))

# Shelf-pack the kept frames into one row, padded so neighbours cannot bleed into each
# other when the canvas samples them at a fractional scale.
PAD = 2
kept = [(k, meta["frames"][k]) for k in KEEP if k in meta["frames"]]
missing = [k for k in KEEP if k not in meta["frames"]]
if missing:
    sys.exit("atlas.json has no frame for: " + ", ".join(missing))
w = sum(f["w"] + PAD for _, f in kept) + PAD
h = max(f["h"] for _, f in kept) + PAD * 2
im = Image.new("RGBA", (w, h), (0, 0, 0, 0))
frames, x = {}, PAD
for k, f in kept:
    im.paste(src.crop((f["x"], f["y"], f["x"] + f["w"], f["y"] + f["h"])), (x, PAD))
    frames[k] = {"x": x, "y": PAD, "w": f["w"], "h": f["h"], "ax": f["ax"], "ay": f["ay"]}
    x += f["w"] + PAD

buf = io.BytesIO()
im.save(buf, format="WEBP", quality=QUALITY, method=6)
webp = buf.getvalue()

payload = {"tilePx": meta.get("tilePx", 48), "w": im.width, "h": im.height, "frames": frames}

block = (
    '<script id="atlas">\n'
    "/* Generated by tools/inline-atlas.py from art/atlas.png -- do not hand-edit. */\n"
    "window.__ATLAS=" + json.dumps(payload, separators=(",", ":")) + ";\n"
    'window.__ATLAS_IMG="data:image/webp;base64,' + base64.b64encode(webp).decode("ascii") + '";\n'
    "</script>"
)

src = open(HTML, encoding="utf-8").read()
existing = re.search(r'<script id="atlas">.*?</script>', src, re.S)
if existing:
    src = src[:existing.start()] + block + src[existing.end():]
else:
    # Ahead of the game script, so window.__ATLAS is there when the game boots.
    marker = "<script>\n(function(){"
    if marker not in src:
        sys.exit("could not find the game script to insert before")
    src = src.replace(marker, block + "\n" + marker, 1)
open(HTML, "w", encoding="utf-8").write(src)

print(f"atlas {im.width}x{im.height}, {len(frames)} of {len(meta['frames'])} frames kept")
print(f"webp q{QUALITY} {len(webp)/1024:.1f}KB -> base64 {len(webp)*4/3/1024:.1f}KB")
print(f"html now {os.path.getsize(HTML)/1024:.0f}KB")
